#!/bin/bash

echo "create a draft article"

echo "filename? >"
read filename

if [ -z "$filename" ]; then
    echo "filename must not be empty"
    exit 1
fi

echo $filename---$(date "+%F %T") > ./data/drafts/${filename}.md
echo ./data/drafts/${filename}.md
